# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               AkashiAkastuki Portfolio
tagline:             ''
description:         '明石暁です'
url:                 http://akashiakatsuki.github.io
baseurl:             ''
paginate:            5
paginate_path:	     "/blog/page:num"
gems:		     [jekyll-paginate]

# About/contact
author:
  name:              Akashi Akatsuki
  url:               https://twitter.com/akashiakatsuki
  email:             b1016082@fun.ac.jp

# Custom vars
version:             1.1.0

kramdown:
  extentions: ["hard_wrap"]
